apiVersion: batch/v1
kind: CronJob
metadata:
  name: backingup
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backingup
            image: adithyagurikar/backup:latest  
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure